//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpFinance
{
    using System;
    using System.Collections.Generic;
    
    public partial class AF_CLIENT
    {
        public string entite { get; set; }
        public string code_clien { get; set; }
        public string NOM { get; set; }
        public string code_wil { get; set; }
        public string cod_activ { get; set; }
        public string activite { get; set; }
        public string cod_sect { get; set; }
        public string secteur { get; set; }
        public string cod_com { get; set; }
        public string commercial { get; set; }
        public string cod_superv { get; set; }
        public string superv { get; set; }
        public Nullable<decimal> obj_an { get; set; }
        public string veille { get; set; }
        public string raison_veil { get; set; }
        public string sup_veille { get; set; }
        public string rai_sveil { get; set; }
        public string cvn_client { get; set; }
        public string chq_gar { get; set; }
        public Nullable<System.DateTime> date_convention { get; set; }
        public string PALIERCVN { get; set; }
        public Nullable<decimal> OBJECTIF_CVN { get; set; }
        public Nullable<System.DateTime> Date_creation { get; set; }
        public string Heure_Creation { get; set; }
        public string cree_par { get; set; }
        public System.DateTime date_extraction { get; set; }
        public string Adesse { get; set; }
        public string ville { get; set; }
        public Nullable<int> CR_JR { get; set; }
        public string ID_FISC { get; set; }
        public string code_aux { get; set; }
        public string RC { get; set; }
        public string L_Wilaya { get; set; }
    }
}
