//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpFinance
{
    using System;
    using System.Collections.Generic;
    
    public partial class AF_ETAT_AVOIR
    {
        public int pkey { get; set; }
        public Nullable<int> IDG { get; set; }
        public string numDossier { get; set; }
        public Nullable<int> numAvoir { get; set; }
        public byte Etat { get; set; }
        public string observation { get; set; }
        public System.DateTime dateHeure { get; set; }
    
        public virtual AVOIR_FINANCIER AVOIR_FINANCIER { get; set; }
    }
}
