//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpFinance
{
    using System;
    using System.Collections.Generic;
    
    public partial class AF_EF_LIGNE_FACTURE
    {
        public string ENTITE { get; set; }
        public decimal NUM_FACT { get; set; }
        public System.DateTime DATE_FACT { get; set; }
        public int NUM_LIGNE { get; set; }
    
        public virtual AF_EF_FACTURE AF_EF_FACTURE { get; set; }
    }
}
