//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpFinance
{
    using System;
    using System.Collections.Generic;
    
    public partial class AF_FACTURES_CLIENTS
    {
        public string entite { get; set; }
        public string type_trans { get; set; }
        public decimal num_trans { get; set; }
        public string code_clien { get; set; }
        public Nullable<decimal> num_ref { get; set; }
        public Nullable<System.DateTime> date_ref { get; set; }
        public string SECT { get; set; }
        public string opperant { get; set; }
        public string superv { get; set; }
        public Nullable<decimal> obj_FC { get; set; }
        public string statut_cvn { get; set; }
        public string cod_wil { get; set; }
        public string cod_comp { get; set; }
        public Nullable<System.DateTime> date_trans { get; set; }
        public Nullable<decimal> total_HT { get; set; }
        public Nullable<decimal> total_TVA { get; set; }
        public Nullable<decimal> T_remise { get; set; }
        public Nullable<decimal> total_TTC { get; set; }
        public string facturier { get; set; }
        public string heure { get; set; }
        public string libelle_secteur { get; set; }
        public string code_commercial { get; set; }
        public string nom_commercial { get; set; }
        public Nullable<double> code_bl { get; set; }
        public Nullable<System.DateTime> date_bl { get; set; }
        public string code_operant { get; set; }
        public int annee_trans { get; set; }
        public Nullable<int> mois_trans { get; set; }
        public Nullable<int> CRJR { get; set; }
        public Nullable<int> CRJRE { get; set; }
        public Nullable<System.DateTime> DATEECH { get; set; }
        public Nullable<decimal> Marge { get; set; }
    }
}
