//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpFinance
{
    using System;
    using System.Collections.Generic;
    
    public partial class AF_MARGE_FACTURES
    {
        public decimal NUM_TRANS { get; set; }
        public Nullable<System.DateTime> DATE_TRANS { get; set; }
        public Nullable<decimal> Marge { get; set; }
    }
}
