//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpFinance
{
    using System;
    using System.Collections.Generic;
    
    public partial class AF_PALIER_EF
    {
        public int idPalier { get; set; }
        public decimal DebutPalier { get; set; }
        public decimal FinPalier { get; set; }
        public decimal Percentage { get; set; }
        public byte actif { get; set; }
    }
}
