//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpFinance
{
    using System;
    using System.Collections.Generic;
    
    public partial class AF_TEMP_AVOIR_FINANCIER
    {
        public int numAvoir { get; set; }
        public System.DateTime dateAvoir { get; set; }
        public decimal montant { get; set; }
        public Nullable<int> numAvoirComptable { get; set; }
        public string designation { get; set; }
        public decimal montantCheque { get; set; }
        public decimal montantCreance { get; set; }
        public string Observation { get; set; }
        public byte typeAvoir { get; set; }
    }
}
