//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpFinance
{
    using System;
    using System.Collections.Generic;
    
    public partial class AF_TEMP_DATA
    {
        public string refAvoir { get; set; }
        public int numAvoir { get; set; }
        public System.DateTime dateAvoir { get; set; }
        public Nullable<decimal> Montant { get; set; }
        public Nullable<decimal> cheque { get; set; }
        public Nullable<decimal> creance { get; set; }
        public string typeAvoir { get; set; }
        public string codeClient { get; set; }
        public string factures { get; set; }
        public string entite { get; set; }
        public Nullable<int> idgroupe { get; set; }
    }
}
