//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpFinance
{
    using System;
    using System.Collections.Generic;
    
    public partial class AVOIR_FINANCIER
    {
        public AVOIR_FINANCIER()
        {
            this.CHEQUE = new HashSet<CHEQUE>();
            this.AF_ETAT_AVOIR = new HashSet<AF_ETAT_AVOIR>();
        }
    
        public int numAvoir { get; set; }
        public System.DateTime dateAvoir { get; set; }
        public decimal montant { get; set; }
        public Nullable<int> numAvoirComptable { get; set; }
        public string designation { get; set; }
        public decimal montantCheque { get; set; }
        public decimal montantCreance { get; set; }
        public string Observation { get; set; }
        public byte typeAvoir { get; set; }
    
        public virtual ICollection<CHEQUE> CHEQUE { get; set; }
        public virtual ICollection<AF_ETAT_AVOIR> AF_ETAT_AVOIR { get; set; }
    }
}
