//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpFinance
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANQUE
    {
        public BANQUE()
        {
            this.CHEQUE = new HashSet<CHEQUE>();
        }
    
        public string ENTITE { get; set; }
        public int CODE_BANQUE { get; set; }
        public string NOM_BANQUE { get; set; }
        public Nullable<int> BANQUE_DEPOT { get; set; }
        public string ADRESSE { get; set; }
        public string NUM_TELEPHONE { get; set; }
        public string ID_USER { get; set; }
        public System.DateTime DATE_SAISIE { get; set; }
    
        public virtual ICollection<CHEQUE> CHEQUE { get; set; }
    }
}
