//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpFinance
{
    using System;
    using System.Collections.Generic;
    
    public partial class LISTE_SPONSOR
    {
        public string CODE_SP { get; set; }
        public string NOM_SP { get; set; }
        public string CODE_TYPE_SP { get; set; }
    }
}
