//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpFinance
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class ExpFinanceEntities : DbContext
    {
        public ExpFinanceEntities()
            : base("name=ExpFinanceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AVOIR_FINANCIER> AVOIR_FINANCIER { get; set; }
        public DbSet<BANQUE> BANQUE { get; set; }
        public DbSet<CHEQUE> CHEQUE { get; set; }
        public DbSet<FACTURE> FACTURE { get; set; }
        public DbSet<GROUPE_FACTURE> GROUPE_FACTURE { get; set; }
        public DbSet<PROMOTION> PROMOTION { get; set; }
        public DbSet<AF_DOSSIER_PROMO> AF_DOSSIER_PROMO { get; set; }
        public DbSet<AF_FACTURES_CLIENTS> AF_FACTURES_CLIENTS { get; set; }
        public DbSet<AF_MARGE_FACTURES> AF_MARGE_FACTURES { get; set; }
        public DbSet<AF_CLIENT> AF_CLIENT { get; set; }
        public DbSet<AF_FACTURE> AF_FACTURE { get; set; }
        public DbSet<AF_GROUPE_FACTURE> AF_GROUPE_FACTURE { get; set; }
        public DbSet<LISTE_SPONSOR> LISTE_SPONSOR { get; set; }
        public DbSet<SPONSORISER> SPONSORISER { get; set; }
        public DbSet<AF_ETAT_AVOIR> AF_ETAT_AVOIR { get; set; }
        public DbSet<AF_AVOIR_GROUPE> AF_AVOIR_GROUPE { get; set; }
        public DbSet<AF_UTILISATEUR> AF_UTILISATEUR { get; set; }
        public DbSet<AF_LIGNE_FACTURE> AF_LIGNE_FACTURE { get; set; }
        public DbSet<AF_PALIER_EF> AF_PALIER_EF { get; set; }
        public DbSet<AF_FACTURES_CLIENTS_ALL> AF_FACTURES_CLIENTS_ALL { get; set; }
        public DbSet<AF_EF_FACTURE> AF_EF_FACTURE { get; set; }
        public DbSet<AF_EF_GROUPE_FACTURE> AF_EF_GROUPE_FACTURE { get; set; }
        public DbSet<AF_EF_LIGNE_FACTURE> AF_EF_LIGNE_FACTURE { get; set; }
        public DbSet<AF_TEMP_AVOIR_FINANCIER> AF_TEMP_AVOIR_FINANCIER { get; set; }
        public DbSet<AF_TEMP_AVOIR_GROUPE> AF_TEMP_AVOIR_GROUPE { get; set; }
        public DbSet<AF_TEMP_DATA> AF_TEMP_DATA { get; set; }
        public DbSet<AF_TEMP_ETAT_AVOIR> AF_TEMP_ETAT_AVOIR { get; set; }
        public DbSet<AF_TEMP_FACTURE> AF_TEMP_FACTURE { get; set; }
        public DbSet<AF_TEMP_GROUPE_FACTURE> AF_TEMP_GROUPE_FACTURE { get; set; }
        public DbSet<AF_TEMP_DATA_ANT> AF_TEMP_DATA_ANT { get; set; }
        public DbSet<AF_FACTURES_CLIENTS_ALL_YEARS> AF_FACTURES_CLIENTS_ALL_YEARS { get; set; }
        public DbSet<AF_OPS_LOG> AF_OPS_LOG { get; set; }
    
        public virtual int GET_FACTURES(string entite)
        {
            var entiteParameter = entite != null ?
                new ObjectParameter("entite", entite) :
                new ObjectParameter("entite", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_FACTURES", entiteParameter);
        }
    
        public virtual int GET_GROUPE_FACTURE(string entite)
        {
            var entiteParameter = entite != null ?
                new ObjectParameter("entite", entite) :
                new ObjectParameter("entite", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_GROUPE_FACTURE", entiteParameter);
        }
    
        [EdmFunction("ExpFinanceEntities", "AF_GET_LIGNES_FACTURE")]
        public virtual IQueryable<AF_GET_LIGNES_FACTURE_Result> AF_GET_LIGNES_FACTURE(string entite, Nullable<int> numt, Nullable<System.DateTime> d)
        {
            var entiteParameter = entite != null ?
                new ObjectParameter("entite", entite) :
                new ObjectParameter("entite", typeof(string));
    
            var numtParameter = numt.HasValue ?
                new ObjectParameter("numt", numt) :
                new ObjectParameter("numt", typeof(int));
    
            var dParameter = d.HasValue ?
                new ObjectParameter("d", d) :
                new ObjectParameter("d", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<AF_GET_LIGNES_FACTURE_Result>("[ExpFinanceEntities].[AF_GET_LIGNES_FACTURE](@entite, @numt, @d)", entiteParameter, numtParameter, dParameter);
        }
    }
}
