//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpFinance
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROMOTION
    {
        public PROMOTION()
        {
            this.GROUPE_FACTURE = new HashSet<GROUPE_FACTURE>();
        }
    
        public int ID_LIGNE { get; set; }
        public int CODE_PROMOTION { get; set; }
        public string NOM_PROMOTION { get; set; }
        public string TYPE_PROMOTION { get; set; }
        public int TYPE_CLIENT { get; set; }
        public string LIBELLE_CADEAU { get; set; }
        public int NOMBRE_SPONSOR { get; set; }
        public Nullable<decimal> MONTANT_BUDGET_PROMOTION { get; set; }
        public Nullable<decimal> MONTANT_PALIER_ATTEINDRE { get; set; }
        public System.DateTime VALIDE_DU { get; set; }
        public System.DateTime VALIDE_AU { get; set; }
        public string ID_USER { get; set; }
        public Nullable<System.DateTime> DATE_SAISIE { get; set; }
        public Nullable<System.DateTime> DATE_MAJ { get; set; }
        public Nullable<int> ETAT { get; set; }
        public Nullable<decimal> TAUX_MARGE_GARDER { get; set; }
        public Nullable<decimal> MTN_MARGE_AD { get; set; }
        public string MOTIF { get; set; }
        public Nullable<decimal> TX_CIBLE { get; set; }
        public Nullable<decimal> TX_DEPENSE { get; set; }
    
        public virtual ICollection<GROUPE_FACTURE> GROUPE_FACTURE { get; set; }
    }
}
